#!/bin/bash

CDGA_INPUT_DIR=${CDGA_INPUT_DIR:-$1}
CDGA_OUTPUT_DIR=${CDGA_OUTPUT_DIR:-$2}

LSB_JOBINDEX=${LSB_JOBINDEX:-$3}
JOB_INDEX=$((LSB_JOBINDEX - 1))

DEFAULT_FILES_PER_JOB=100
FILES_PER_JOB=${FILES_PER_JOB:-$DEFAULT_FILES_PER_JOB}
INPUT_INDEX=$((JOB_INDEX * FILES_PER_JOB))

echo "Gradient Adjustment Job $LSB_JOBINDEX: $INPUT_INDEX"

local/scripts/runGradAdjustment.sh \
    "${CDGA_INPUT_DIR}:${INPUT_INDEX}:${FILES_PER_JOB}" ${CDGA_OUTPUT_DIR} > ga_${LSB_JOBINDEX}.log
